//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaraCroftFansClient.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A37A16_zaghiniEntities : DbContext
    {
        public DB_A37A16_zaghiniEntities()
            : base("name=DB_A37A16_zaghiniEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<posts> posts { get; set; }
        public virtual DbSet<tags> tags { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<usertype> usertype { get; set; }
        public virtual DbSet<section> section { get; set; }
        public virtual DbSet<sectionitem> sectionitem { get; set; }
    }
}
