//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaraCroftFansClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sectionitem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sectionitem()
        {
            this.section1 = new HashSet<section>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public bool active { get; set; }
        public bool onlyregistercanread { get; set; }
        public int idsection { get; set; }
        public string image { get; set; }
    
        public virtual section section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<section> section1 { get; set; }
    }
}
